// Symbol Vault & Kaomoji library for nicknamegenerator.io

export interface SymbolCategory {
  category: string;
  description: string;
  symbols: string[];
}

export const SYMBOL_CATEGORIES: SymbolCategory[] = [
  {
    category: "Pro Gamer & Flairs",
    description: "Legendary gaming flairs, tails, and rare signs used in Free Fire & PUBG",
    symbols: [
      "᭄",
      "࿐",
      "亗",
      "x͜×",
      "╰‿╯",
      "ঔৣ",
      "☬",
      "༒",
      "༺",
      "༻",
      "ㅤ", // Invisible Space U+3164
      "〆",
      "⸙",
      "☂️",
      "🐲",
      "☯︎",
      "ツ",
      "彡",
      "々",
      "メ",
      "父",
      "乡",
      "⓿❸",
      "⁹⁹⁹⁺",
    ],
  },
  {
    category: "Guns & Combat",
    description: "Sniper crosshairs, weapons, daggers, and battle icons for shooters",
    symbols: [
      "︻╦̵̵͇̿̿̿̿╤──",
      "︻╦デ╤━一",
      "▄︻̷̿┻̿═━一",
      "╾━╤デ╦︻",
      "⚔️",
      "🗡️",
      "🏹",
      "☠️",
      "☣️",
      "⚡",
      "𒀱",
      "☬",
      "亗",
      "ᜰ꙰ꦿ➢",
      "x͜×",
      "†",
      "‡",
      "𖤍",
      "☠",
      "⚚",
      "༒",
    ],
  },
  {
    category: "Wings & Angels",
    description: "Legendary angel and demon wings used by top rank players",
    symbols: [
      "꧁༒",
      "༒꧂",
      "꧁༺",
      "༻꧂",
      "༒☬",
      "☬༒",
      "╰‿╯",
      "༺",
      "༻",
      "ʚĭɞ",
      "༇",
      "༆",
      "ʚ",
      "ɞ",
      "༉",
      "꒰",
      "꒱",
      "ಇ",
      "ಌ",
      "ᨐ",
      "༓",
    ],
  },
  {
    category: "Crowns & Royal",
    description: "Kings, queens, emperor crowns and prestige symbols",
    symbols: [
      "👑",
      "亗",
      "♕",
      "♚",
      "♛",
      "♔",
      "💎",
      "✦",
      "★",
      "✫",
      "✪",
      "✬",
      "✮",
      "✯",
      "✰",
      "✧",
      "⚜️",
      "⚜",
      "☬",
      "◈",
      "💍",
    ],
  },
  {
    category: "Japanese & Anime",
    description: "Authentic Japanese Kanji, Katakana, and anime gamer tags",
    symbols: [
      "メ",
      "ツ",
      "シ",
      "々",
      "父",
      "乡",
      "气",
      "鬼",
      "神",
      "死",
      "愛",
      "龍",
      "影",
      "王",
      "虎",
      "刃",
      "魔",
      "夜",
      "月",
      "桜",
      "侍",
      "忍",
      "焔",
      "狂",
    ],
  },
  {
    category: "Aesthetic & Hearts",
    description: "Soft aesthetic hearts, sparkles, stars, and cute floral symbols",
    symbols: [
      "♡",
      "ᥫ᭡",
      "♥",
      "❥",
      "ღ",
      "❣",
      "✿",
      "❀",
      "❁",
      "🌸",
      "✨",
      "☁️",
      "⋆｡˚",
      "˚₊‧",
      "‧₊˚",
      "༘",
      "𓈒𓏸",
      "𓂋",
      "ꕤ",
      "🪻",
      "🪽",
      "🌙",
      "ʚ",
    ],
  },
  {
    category: "Brackets & Dividers",
    description: "Clan borders, clan tag brackets, and symmetry frames",
    symbols: [
      "『",
      "』",
      "【",
      "】",
      "〖",
      "〗",
      "〔",
      "〕",
      "《",
      "》",
      "「",
      "」",
      "⟦",
      "⟧",
      "◥",
      "◤",
      "◢",
      "◣",
      "»",
      "«",
      "░",
      "▒",
      "▓",
      "─═━",
      "━═─",
      "·.★·.",
      ".·´¯`·.",
    ],
  },
  {
    category: "Kaomojis & Faces",
    description: "Expressive Japanese emoticons for gamertags and bios",
    symbols: [
      "( ͡° ͜ʖ ͡°)",
      "(•‿•)",
      "(▀̿Ĺ̯▀̿ ̿)",
      "(ง'̀-'́)ง",
      "ʕ•ᴥ•ʔ",
      "(◕‿◕✿)",
      "(づ｡◕‿‿◕｡)づ",
      "(>_<)",
      "(¬_¬)",
      "¯\\_(ツ)_/¯",
      "(╯°□°)╯︵ ┻━┻",
      "ಠ_ಠ",
      "(｡♥‿♥｡)",
      "(✿◠‿◠)",
      "ヽ(´▽`)/",
    ],
  },
];
